micronaut:
  application:
    name: demo

redis:
  uri: redis://localhost
  caches:
    blocking-example-cache:
      expire-after-write: 10m
      value-serializer: io.micronaut.jackson.serialize.JacksonObjectSerializer
    reactive-example-cache:
      expire-after-write: 10m
      value-serializer: io.micronaut.jackson.serialize.JacksonObjectSerializer